#!/bin/bash

set -e

# Issue - https://github.com/docker/hub-feedback/issues/384#issuecomment-214508878
# Docker Hub emits an invalid .dockercfg.  Remove the outer auths element.
if [[ $DOCKERCFG == {\"auths\":* ]]; then
    jsonStartIndex=$(expr index "$DOCKERCFG" :)
    length=$((${#DOCKERCFG} - $jsonStartIndex - 1))
    echo ${DOCKERCFG:jsonStartIndex:length} > /root/.dockercfg
fi


echo "Pushing onbuild image"
versionedImageName=$repoName":rel-1.0.0-preview2.1-onbuild"
docker tag onbuild $versionedImageName
docker push $versionedImageName
