#!/bin/bash

set -e

# Issue - https://github.com/docker/hub-feedback/issues/384#issuecomment-214508878
# Docker Hub emits an invalid .dockercfg.  Remove the outer auths element.
if [[ $DOCKERCFG == {\"auths\":* ]]; then
    jsonStartIndex=$(expr index "$DOCKERCFG" :)
    length=$((${#DOCKERCFG} - $jsonStartIndex - 1))
    echo ${DOCKERCFG:jsonStartIndex:length} > /root/.dockercfg
fi


echo "Pushing latest runtime-deps image"
tagStartIndex=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStartIndex - 1}
latestImageName=$repoName":runtime-deps"
docker tag $IMAGE_NAME $latestImageName
docker push $latestImageName


echo "Pushing runtime images"
versionedImageName=$repoName":rel-1.0.0-runtime"
docker tag runtime $versionedImageName
docker push $versionedImageName

latestImageName=$repoName":runtime"
docker tag runtime $latestImageName
docker push $latestImageName
